### ISSUE TITLE
Intermittent sprite glitch

### ISSUE THREAD

**Issue by tonylukasavage** [BloodSweatAndCode/cv2r#21] opened 2019-07-27 15:37 UTC
Seems to occur most frequently at dead river and with spiders

* https://clips.twitch.tv/GentleEphemeralFoxMingLee
* https://clips.twitch.tv/WanderingAbnegateRadicchioDoggo

**Comment by BloodSweatAndCode** [comment] 2019-09-06 02:00
seems to be spiders, particularly when they are placed high

**Comment by BloodSweatAndCode** [comment] 2019-09-10 13:10
A solution here can also resolve the suicide spiders as well

**Comment by BloodSweatAndCode** [comment] 2019-09-10 15:11
I have attempted to reproduce this a million different ways and can't cause the issue in latest master. It may have been resolved by using the Camilla sprite table instead of the Death one for all mansion enemy spawns, done in https://github.com/BloodSweatAndCode/cv2r/pull/75, which fixed the "low priority" sprite rendering. I think this might be the case because both examples above see the glitch with a spider's "line" when using the mansion sprite table, and the mansion sprite table for Camilla has slightly different properties than the Death one.

**Closed by BloodSweatAndCode** 2019-09-10 15:11 UTC
Labels: bug
